const Student = require('./student')
const Teacher = require('./teacher')
const ClassGroup = require('./classgroup')

const classGroup3A = new ClassGroup(3, 'A')
const classGroup4B = new ClassGroup(4, 'B')

const Burak = new Student('Burak', 'Guzel', 3, 'A')
const WhoAmI = new Student('WhoAmI', 'Unknown', 3, 'A')
const MrX = new Teacher('Mr', 'X', 3, 'A')
const MrsY = new Teacher('Mrs', 'Y', 4, 'B')
const StudentZ = new Student('Student', 'Z', 4, 'B')

Burak.joinClass(classGroup3A)
WhoAmI.joinClass(classGroup3A)
MrX.joinClass(classGroup3A)
StudentZ.joinClass(classGroup4B)
MrsY.joinClass(classGroup4B)
console.log(classGroup3A.details)
console.log(classGroup4B.details)